from pydantic import BaseModel

# class ImageCreate(BaseModel):  
#     image: str
#     authenticationDate: str

# class ImageBase(BaseModel):
#     image: str
#     authenticationDate: str

# class Image(ImageBase):
#     uid: int

#     class Config:
#         orm_mode = True

class ImageBase(BaseModel):
    image: str  # File name of the uploaded image

class ImageCreate(ImageBase):  # For creating new images
    pass

class Image(ImageBase):  # For returning saved images
    uid: int
    authenticationDate: str  # Auto-generated by the database

    class Config:
        orm_mode = True
